/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.iniciosesion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class SeleccionarAlbum extends javax.swing.JFrame {
    private CrearPublicacion anterior;
    public SeleccionarAlbum(CrearPublicacion aThis) {
        initComponents();
        btnNuevo.setBorder(new BordePunteado());
        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.Y_AXIS)); // uno debajo del otro
        this.anterior = aThis;
        cargarAlbumes(); // ← esto se ejecutará cada vez que se abra
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Seleccionar álbum");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equi2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mas2.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Crear álbum");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panelContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CrearPublicacion ventana = new CrearPublicacion(); // ← sin parámetros
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        CrearAlbum ventana = new CrearAlbum(anterior); // ← sin parámetros
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto1;
    private javax.swing.JButton btnFoto2;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreAlbum1;
    private javax.swing.JLabel lblNombreAlbum4;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

private void cargarAlbumes() {
    panelContenedor.removeAll();
    int idUsuario = IniciarSesion.idUsuario;

    String sql = """
        SELECT a.ID_Album, a.Nombre, a.Portada_album, COUNT(m.ID_Media) AS CantidadFotos
        FROM album a
        LEFT JOIN media m ON a.ID_Album = m.ID_Album AND m.Tipo = 'imagen'
        WHERE a.ID_Usuario = ?
        GROUP BY a.ID_Album
    """;

    try (
        Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/facebook", "AlanMijares", "1");
        PreparedStatement ps = con.prepareStatement(sql)
    ) {
        ps.setInt(1, idUsuario);
        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                int idAlbum = rs.getInt("ID_Album");
                String nombreAlbum = rs.getString("Nombre");
                int cantidad = rs.getInt("CantidadFotos");
                byte[] portadaBytes = rs.getBytes("Portada_album");

                JButton btnFoto = new JButton();
                btnFoto.setPreferredSize(new Dimension(100, 80));
                btnFoto.setContentAreaFilled(false);
                btnFoto.setBorderPainted(false);
                btnFoto.setFocusPainted(false);

                if (portadaBytes != null) {
                    ImageIcon portadaIcon = new ImageIcon(portadaBytes);
                    Image imagenEscalada = portadaIcon.getImage().getScaledInstance(100, 80, Image.SCALE_SMOOTH);
                    btnFoto.setIcon(new ImageIcon(imagenEscalada));
                    btnFoto.setText("");
                } else {
                    btnFoto.setText("FOTO");
                    btnFoto.setContentAreaFilled(true);
                    btnFoto.setBorderPainted(true);
                }

                // Seleccionar portada al hacer clic derecho
                btnFoto.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        if (SwingUtilities.isRightMouseButton(e)) {
                            JFileChooser fileChooser = new JFileChooser();
                            fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg", "gif"));
                            int resultado = fileChooser.showOpenDialog(null);

                            if (resultado == JFileChooser.APPROVE_OPTION) {
                                File archivo = fileChooser.getSelectedFile();
                                try {
                                    byte[] imagenBytes = Files.readAllBytes(archivo.toPath());

                                    try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/facebook", "AlanMijares", "1");
                                         PreparedStatement stmt = conn.prepareStatement("UPDATE album SET Portada_album = ? WHERE ID_Album = ?")) {

                                        stmt.setBytes(1, imagenBytes);
                                        stmt.setInt(2, idAlbum);
                                        stmt.executeUpdate();

                                        ImageIcon icono = new ImageIcon(imagenBytes);
                                        Image escalada = icono.getImage().getScaledInstance(100, 80, Image.SCALE_SMOOTH);
                                        btnFoto.setIcon(new ImageIcon(escalada));
                                        btnFoto.setText("");

                                        JOptionPane.showMessageDialog(null, "Portada actualizada.");
                                    }

                                } catch (IOException | SQLException ex) {
                                    JOptionPane.showMessageDialog(null, "Error al establecer la portada: " + ex.getMessage());
                                }
                            }
                        }
                    }
                });

                JLabel lblNombre = new JLabel(nombreAlbum);
                JLabel lblFotos = new JLabel(cantidad + " foto" + (cantidad != 1 ? "s" : ""));

                btnFoto.addActionListener(e -> {
                    String texto = anterior.getTextoo().getText();
                    ImageIcon imagenActual = (ImageIcon) anterior.getImag().getIcon();
                    String privacidad = anterior.getPrivacidadCombo().getSelectedItem().toString();

                    CrearPublicacion crear = new CrearPublicacion(texto, imagenActual, nombreAlbum, idAlbum, privacidad);
                    crear.setVisible(true);
                    anterior.dispose();
                    this.dispose();
                });

                JPanel panelAlbum = new JPanel(new BorderLayout());
                panelAlbum.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                panelAlbum.add(btnFoto, BorderLayout.WEST);

                JPanel textoPanel = new JPanel(new GridLayout(2, 1));
                textoPanel.add(lblNombre);
                textoPanel.add(lblFotos);
                panelAlbum.add(textoPanel, BorderLayout.CENTER);

                panelContenedor.add(panelAlbum);
            }
        }

        panelContenedor.revalidate();
        panelContenedor.repaint();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar álbumes: " + e.getMessage());
    }
}
}

